// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Kye.SistemasRegistros.Repositorio.Models;

public partial class BitacorasSistema
{
    public int Idbitacora { get; set; }

    public int Idusuario { get; set; }

    public DateTime FechaAccion { get; set; }

    public string TablaAfectada { get; set; }

    public string TipoAccion { get; set; }

    public string Descripcion { get; set; }

    public bool StatusActivo { get; set; }

    public virtual Usuario IdusuarioNavigation { get; set; }
}