// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Kye.SistemasRegistros.Repositorio.Models;

public partial class ContactosEmergencia
{
    public int Idemergencia { get; set; }

    public int Idmiembro { get; set; }

    public string NombreContacto { get; set; }

    public string Parentesco { get; set; }

    public string TelefonoContacto { get; set; }

    public bool StatusActivo { get; set; }

    public virtual Miembro IdmiembroNavigation { get; set; }
}