// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Kye.SistemasRegistros.Repositorio.Models;

public partial class Logo
{
    public int Idlogo { get; set; }

    public string NombreLogo { get; set; }

    public int Ancho { get; set; }

    public int Alto { get; set; }

    public byte[] Imagen { get; set; }

    public string Descripcion { get; set; }

    public bool StatusActivo { get; set; }
}