// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Kye.SistemasRegistros.Repositorio.Models;

public partial class Membresia
{
    public int Idmembresia { get; set; }

    public int Idmiembro { get; set; }

    public int Idplan { get; set; }

    public DateTime FechaInicio { get; set; }

    public DateTime? FechaFin { get; set; }

    public DateTime? FechaProximoPago { get; set; }

    public string StatusMembresia { get; set; }

    public string ColorSemaforo { get; set; }

    public string Observaciones { get; set; }

    public bool StatusActivo { get; set; }

    public virtual Miembro IdmiembroNavigation { get; set; }

    public virtual Plane IdplanNavigation { get; set; }

    public virtual ICollection<Pago> Pagos { get; set; } = new List<Pago>();
}