// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Kye.SistemasRegistros.Repositorio.Models;

public partial class Miembro
{
    public int Idmiembro { get; set; }

    public string NombreCompleto { get; set; }

    public DateTime? FechaNacimiento { get; set; }

    public string Fotografia { get; set; }

    public string Celular { get; set; }

    public string WhatsApp { get; set; }

    public string CorreoElectronico { get; set; }

    public DateTime FechaRegistro { get; set; }

    public byte[] Idhuella { get; set; }

    public bool StatusActivo { get; set; }

    public int IdusuarioRegistro { get; set; }

    public virtual ICollection<Checkin> Checkins { get; set; } = new List<Checkin>();

    public virtual ICollection<ContactosEmergencia> ContactosEmergencia { get; set; } = new List<ContactosEmergencia>();

    public virtual Usuario IdusuarioRegistroNavigation { get; set; }

    public virtual ICollection<Membresia> Membresia { get; set; } = new List<Membresia>();
}