// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Kye.SistemasRegistros.Repositorio.Models;

public partial class Pago
{
    public int Idpago { get; set; }

    public int Idmembresia { get; set; }

    public int IdusuarioCobro { get; set; }

    public DateTime FechaPago { get; set; }

    public decimal MontoPagado { get; set; }

    public decimal? DescuentoAplicado { get; set; }

    public string MetodoPago { get; set; }

    public string Comentario { get; set; }

    public bool StatusActivo { get; set; }

    public virtual Membresia IdmembresiaNavigation { get; set; }

    public virtual Usuario IdusuarioCobroNavigation { get; set; }
}