// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Kye.SistemasRegistros.Repositorio.Models;

public partial class Plane
{
    public int Idplan { get; set; }

    public string NombrePlan { get; set; }

    public decimal CostoBase { get; set; }

    public int? DuracionMeses { get; set; }

    public bool TienePromocion { get; set; }

    public string DescripcionPromocion { get; set; }

    public DateTime? FechaInicioPromocion { get; set; }

    public DateTime? FechaFinPromocion { get; set; }

    public string TipoDescuento { get; set; }

    public decimal? ValorDescuento { get; set; }

    public bool StatusActivo { get; set; }

    public virtual ICollection<Membresia> Membresia { get; set; } = new List<Membresia>();
}