// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Kye.SistemasRegistros.Repositorio.Models;

public partial class Usuario
{
    public int Idusuario { get; set; }

    public string NombreUsuario { get; set; }

    public string ContraseñaHash { get; set; }

    public string Rol { get; set; }

    public bool StatusActivo { get; set; }

    public virtual ICollection<BitacorasSistema> BitacorasSistemas { get; set; } = new List<BitacorasSistema>();

    public virtual ICollection<Miembro> Miembros { get; set; } = new List<Miembro>();

    public virtual ICollection<Pago> Pagos { get; set; } = new List<Pago>();
}